import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import ThemeProvider from "./components/Providers/ThemeProvider";
import Tabs from "./components/Tabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html   lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <div id="overlay"></div>  
        <Header/>
        <Tabs/>
        {children}
        </ThemeProvider>
       </body>
    </html>
  );
}
